apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v91j1ytzt-nodejs 
  janus-idp.io/tekton: v91j1ytzt-nodejs
  backstage.io/kubernetes-id: v91j1ytzt-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v91j1ytzt-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml